before_script:
  - cmake --version
  - make --version

stages:
  - build
  - test
  - sonar
  
include:
  - local: 'learning/.gitlab-ci.yml'
  - local: 'learning-ri/.gitlab-ci.yml'
  - local: 'unit-simple/.gitlab-ci.yml'
  - local: 'unit-simple-ri/.gitlab-ci.yml'

sonar:
  stage: sonar
  script:
    - $SONAR_SCANNER_HOME/bin/sonar-scanner -Dsonar.login=$SONAR_LOGIN
  artifacts:
    expire_in: 2 days

