build-unit-simple-ri:
  stage: build
  script:
    - cd unit-simple-ri
    - cmake .
    - make
  artifacts:
    expire_in: 2 days

test-unit-simple-ri:
  stage: test
  script:
    - cd unit-simple-ri
    - cmake .
    - make
    - make test
  artifacts:
    expire_in: 2 days

