build-learning-ri:
  stage: build
  script:
    - cd learning-ri
    - cmake -DCMAKE_CXX_STANDARD=17 .
    - make
  artifacts:
    expire_in: 2 days

test-learning-ri:
  stage: test
  script:
    - cd learning-ri
    - cmake -DCMAKE_CXX_STANDARD=17 .
    - make
    - ctest -V --output-on-failure
  artifacts:
    expire_in: 2 days

